import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './styles-extra.css';
import './cases.css';
import './dashboard.css';
import './case-filters.css';
import './meetings.css';
import './account.css';
import './theme-light-blue.css';
import './responsive.css';
import './details-notifications.css';
import './team-workload.css';
import './pagination.css';
import './remember-me.css';
import './refresh.css';
import './standby.css';
import './standby-holidays.css';
import './nicepay-brand.css';
import './theme-selector.css';
import './dark-mode-fixes.css';
import './dark-notifications-workload.css';
import './color-themes.css';
import './more-color-themes.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
