import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './styles-extra.css';
import './cases.css';
import './dashboard.css';
import './case-filters.css';
import './meetings.css';
import './account.css';
import './theme-light-blue.css';
import './responsive.css';
import './details-notifications.css';
import './team-workload.css';
import './pagination.css';
import './remember-me.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
