import { useEffect, useMemo, useState } from 'react';
import { CalendarCheck, Plus, RefreshCw, Save, Trash2, UsersRound } from 'lucide-react';
import { api } from './api';

type Member={id:string;name:string;email:string;role:string;standbyGroup?:string|null};
type Schedule={id:string;scheduleDate:string;groupName:string;member:Member};
type Holiday={id:string;holidayDate:string;name:string;holidayType:'PUBLIC_HOLIDAY'|'JOINT_HOLIDAY'};
const currentMonth=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit'}).format(new Date());
const todayJakarta=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

export default function StandbyPage({members,onMembersChanged}:{members:Member[];onMembersChanged:()=>void}){
  const user=JSON.parse(localStorage.getItem('mp_user')||'{"role":""}');
  const canManage=/\blead\b/i.test(user.role||'');
  const staffMembers=useMemo(()=>members.filter(member=>/\bstaff\b/i.test(member.role||'')),[members]);
  const [month,setMonth]=useState(currentMonth());
  const [items,setItems]=useState<Schedule[]>([]);
  const [holidays,setHolidays]=useState<Holiday[]>([]);
  const [holidayForm,setHolidayForm]=useState({holidayDate:'',name:'',holidayType:'PUBLIC_HOLIDAY'});
  const [drafts,setDrafts]=useState<Record<string,string>>(Object.fromEntries(staffMembers.map(member=>[member.id,member.standbyGroup||''])));
  const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');
  async function load(){const [scheduleData,holidayData]=await Promise.all([api(`/standby?month=${month}`),api(`/standby/holidays?month=${month}`)]);setItems(scheduleData);setHolidays(holidayData)}
  useEffect(()=>{load().catch(value=>setError((value as Error).message))},[month]);
  useEffect(()=>setDrafts(Object.fromEntries(staffMembers.map(member=>[member.id,member.standbyGroup||'']))),[staffMembers]);
  const scheduleByDate=useMemo(()=>{const grouped=new Map<string,{group1?:Member;group2?:Member}>();for(const item of items){const row=grouped.get(item.scheduleDate)||{};if(item.groupName==='GROUP_1')row.group1=item.member;else row.group2=item.member;grouped.set(item.scheduleDate,row)}return grouped},[items]);
  const holidayByDate=useMemo(()=>new Map(holidays.map(holiday=>[holiday.holidayDate,holiday])),[holidays]);
  const calendarCells=useMemo(()=>{const [year,monthNumber]=month.split('-').map(Number);const daysInMonth=new Date(year,monthNumber,0).getDate();const leading=(new Date(year,monthNumber-1,1).getDay()+6)%7;return [...Array(leading).fill(null),...Array.from({length:daysInMonth},(_,index)=>index+1)]},[month]);
  async function saveGroups(){setBusy('groups');setError('');setMessage('');try{await api('/standby/groups',{method:'PATCH',body:JSON.stringify({assignments:staffMembers.map(member=>({userId:member.id,groupName:drafts[member.id]||null}))})});setMessage('Standby groups saved.');onMembersChanged()}catch(value){setError((value as Error).message)}finally{setBusy('')}}
  async function saveHoliday(event:React.FormEvent){event.preventDefault();setBusy('holiday');setError('');setMessage('');try{await api('/standby/holidays',{method:'POST',body:JSON.stringify(holidayForm)});setHolidayForm({holidayDate:'',name:'',holidayType:'PUBLIC_HOLIDAY'});await load();setMessage(holidayForm.holidayType==='PUBLIC_HOLIDAY'?'Public holiday saved. Standby is disabled for that date.':'Joint holiday saved. Standby remains active.')}catch(value){setError((value as Error).message)}finally{setBusy('')}}
  async function removeHoliday(holiday:Holiday){if(!window.confirm(`Remove ${holiday.name}?`))return;await api(`/standby/holidays/${holiday.id}`,{method:'DELETE'});await load()}
  async function generate(){if(!window.confirm(`Generate a new randomized standby calendar for ${month}? Existing assignments for this month will be replaced.`))return;setBusy('generate');setError('');setMessage('');try{setItems(await api('/standby/generate',{method:'POST',body:JSON.stringify({month})}));setMessage('Weekday standby calendar generated successfully.')}catch(value){setError((value as Error).message)}finally{setBusy('')}}
  return <main className="content standby-page"><header><div><p className="eyebrow">TEAM OPERATIONS</p><h1>Standby schedule</h1><p className="muted">Two rotating groups, scheduled fairly on weekdays only.</p></div>{canManage&&<button className="primary" disabled={!!busy} onClick={generate}><RefreshCw className={busy==='generate'?'spinning':''}/>Generate calendar</button>}</header>
    {canManage&&<section className="standby-groups"><div className="standby-section-title"><div><UsersRound/><span><h2>Group membership</h2><p className="muted">Only Staff positions are eligible. Assign each staff member before generating the calendar.</p></span></div><button disabled={!!busy} onClick={saveGroups}><Save/>{busy==='groups'?'Saving…':'Save groups'}</button></div><div className="standby-member-grid">{staffMembers.map(member=><label key={member.id}><span><b>{member.name}</b><small>{member.role}</small></span><select value={drafts[member.id]||''} onChange={event=>setDrafts({...drafts,[member.id]:event.target.value})}><option value="">Not assigned</option><option value="GROUP_1">Group 1</option><option value="GROUP_2">Group 2</option></select></label>)}</div>{!staffMembers.length&&<p className="empty">No users with a Staff position were found.</p>}</section>}
    {canManage&&<section className="standby-holidays"><div><h2>Holiday settings</h2><p className="muted">Public holidays have no standby. Joint holidays continue with the normal schedule.</p></div><form onSubmit={saveHoliday}><label>Date<input required type="date" value={holidayForm.holidayDate} onChange={event=>setHolidayForm({...holidayForm,holidayDate:event.target.value})}/></label><label>Holiday name<input required value={holidayForm.name} onChange={event=>setHolidayForm({...holidayForm,name:event.target.value})} placeholder="Holiday name"/></label><label>Type<select value={holidayForm.holidayType} onChange={event=>setHolidayForm({...holidayForm,holidayType:event.target.value})}><option value="PUBLIC_HOLIDAY">Public holiday — no standby</option><option value="JOINT_HOLIDAY">Joint holiday — standby continues</option></select></label><button disabled={!!busy}><Plus/>{busy==='holiday'?'Saving…':'Add holiday'}</button></form>{!!holidays.length&&<div className="holiday-list">{holidays.map(holiday=><article key={holiday.id}><span><b>{new Date(`${holiday.holidayDate}T00:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})} · {holiday.name}</b><small className={holiday.holidayType.toLowerCase()}>{holiday.holidayType==='PUBLIC_HOLIDAY'?'Public holiday · no standby':'Joint holiday · standby active'}</small></span><button title="Remove holiday" onClick={()=>removeHoliday(holiday)}><Trash2/></button></article>)}</div>}</section>}
    {error&&<p className="error standby-feedback">{error}</p>}{message&&<p className="success standby-feedback">{message}</p>}
    <section className="table-card standby-calendar"><div className="table-head"><div><h2>Monthly calendar</h2><p className="muted">One standby member from each group per weekday.</p></div><label>Month<input type="month" value={month} onChange={event=>setMonth(event.target.value)}/></label></div><div className="calendar-weekdays">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(day=><b key={day}>{day}</b>)}</div><div className="standby-calendar-grid">{calendarCells.map((day,index)=>{if(!day)return <div className="calendar-blank" key={`blank-${index}`}/>;const date=`${month}-${String(day).padStart(2,'0')}`;const nativeDay=new Date(`${date}T00:00:00`).getDay();const weekend=nativeDay===0||nativeDay===6;const schedule=scheduleByDate.get(date);const holiday=holidayByDate.get(date);const publicHoliday=holiday?.holidayType==='PUBLIC_HOLIDAY';return <article key={date} className={`${weekend?'calendar-weekend':''} ${publicHoliday?'calendar-public-holiday':''} ${holiday?.holidayType==='JOINT_HOLIDAY'?'calendar-joint-holiday':''} ${date===todayJakarta()?'calendar-today':''}`}><header><b>{day}</b>{date===todayJakarta()&&<span>Today</span>}</header>{holiday&&<div className="calendar-holiday-label"><b>{holiday.name}</b><small>{publicHoliday?'PUBLIC HOLIDAY · NO STANDBY':'JOINT HOLIDAY · STANDBY ACTIVE'}</small></div>}{publicHoliday?<p>No standby</p>:weekend?<p>Weekend</p>:schedule?<div className="calendar-assignments"><div className="group-one" title={schedule.group1?.email}><small>GROUP 1</small><b>{schedule.group1?.name||'Not assigned'}</b></div><div className="group-two" title={schedule.group2?.email}><small>GROUP 2</small><b>{schedule.group2?.name||'Not assigned'}</b></div></div>:<p>No schedule</p>}</article>})}</div>{!items.length&&<div className="calendar-empty-note"><CalendarCheck/><span>No standby assignments generated for this month yet.</span></div>}</section>
  </main>;
}
